export const IS_TRACKING_HYDRATION = "IS_TRACKING_HYDRATION";

export const IS_TRACKING_EATING = "IS_TRACKING_EATING";

export const IS_TRACKING_SLEEP = "IS_TRACKING_SLEEP";

export const IS_TRACKING_EXERCISE = "IS_TRACKING_EXERCISE";

export const UPDATE_DAYS_EXERCISE_PER_WEEK = "UPDATE_DAYS_EXERCISE_PER_WEEK";

export const ENABLE_PUSH_NOTIFICATIONS = "ENABLE_PUSH_NOTIFICATIONS";

export const UPDATE_SCHEDULE_TIME = "UPDATE_SCHEDULE_TIME";
