export const IS_TRACKING_HYDRATION = "IS_TRACKING_HYDRATION";

export const IS_TRACKING_EATING = "IS_TRACKING_EATING";

export const IS_TRACKING_SLEEP = "IS_TRACKING_SLEEP";

export const IS_TRACKING_EXERCISE = "IS_TRACKING_EXERCISE";
